name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # run every 10 a.m., which is UTC 2 a.m + 8
    - cron:  '5 * * * *'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - name: Check out code
        uses: actions/checkout@v2
      
      - name: install
        run: |
          pip3 install beautifulsoup4
          pip3 install requests
        
      - name: run
        run: STD_ID=${{ secrets.STD_ID }} PASSWORD=${{ secrets.PASSWORD }} TOKEN=${{ secrets.TOKEN }} python3 main.py
      
      - name: update
        run: |
          git add *
          git commit -m "automatic update of records"
          git push origin main
